/*

	SCENARIO BACKUP PRATIQUE
https://www.mssqltips.com/sqlservertip/5028/sql-server-2017-differential-backup-changes/

http://www.sqlservergeeks.com/smart-differential-backup/
*/

--Exemple de restauration
	ALTER DATABASE RAN_ATOFFICE
	SET SINGLE_USER
	WITH ROLLBACK IMMEDIATE;
	GO
	RESTORE DATABASE [RAN_ATOFFICE] FROM  DISK = N'C:\DATA\BKP\RAN_ATOFFICE_Full_20171214114750.bak' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  REPLACE,  STATS = 10
	GO
	RESTORE DATABASE [RAN_ATOFFICE] FROM  DISK = N'C:\DATA\BKP\RAN_ATOFFICE_Diff_20171214115028.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 10
	GO
	ALTER DATABASE RAN_ATOFFICE
	SET MULTI_USER;
	GO
